require('dotenv').config();
const express=require('express');const cors=require('cors');const http=require('http');const path=require('path');const fs=require('fs');const rateLimit=require('express-rate-limit');
const {pool}=require('./db');const {limits,rateLimit:rateConfig}=require('./config');const authRoutes=require('./routes/auth');const deliveryRoutes=require('./routes/deliveries');const assignmentRoutes=require('./routes/assignments');const statusRoutes=require('./routes/status');const ratingRoutes=require('./routes/ratings');const wsHub=require('./websocket/hub');
const app=express();app.set('trust proxy',1);
const allowedOrigins=(process.env.ALLOWED_ORIGINS||'').split(',').map(o=>o.trim()).filter(Boolean);
app.use(cors({origin:allowedOrigins,methods:['GET','POST','PUT','PATCH','DELETE','OPTIONS'],allowedHeaders:['Content-Type','Authorization'],credentials:false}));
app.use(express.json({limit:limits.jsonBodyBytes}));
app.use('/api/auth',rateLimit({windowMs:rateConfig.authWindowMs,max:rateConfig.authMax,standardHeaders:true,legacyHeaders:false,message:{error:'Too many auth attempts. Try again later.'}}));
app.use('/api',rateLimit({windowMs:rateConfig.apiWindowMs,max:rateConfig.apiMax,standardHeaders:true,legacyHeaders:false,message:{error:'Too many requests. Slow down.'}}));
app.use('/api/auth',authRoutes);app.use('/api/deliveries',deliveryRoutes);app.use('/api/assignments',assignmentRoutes);app.use('/api/status',statusRoutes);app.use('/api/ratings',ratingRoutes);app.get('/api/health',(req,res)=>res.json({ok:true}));app.use(express.static(path.join(__dirname,'..','..','frontend','public')));app.use((err,req,res,next)=>{console.error(err);res.status(err.status||500).json({error:'Internal server error'});});
const server=http.createServer(app);wsHub.init(server);const PORT=process.env.PORT||3000;
async function initializeDatabase(){const result=await pool.query("SELECT to_regclass('public.users') AS table_name");if(result.rows[0].table_name)return;await pool.query(fs.readFileSync(path.join(__dirname,'..','schema.sql'),'utf8'));}
async function ensureSchemaUpgrades(){
 await pool.query("ALTER TYPE delivery_status ADD VALUE IF NOT EXISTS 'STUCK_IN_TRANSIT'");
 await pool.query('ALTER TABLE delivery_requests ADD COLUMN IF NOT EXISTS delivery_code TEXT');
 await pool.query(`UPDATE delivery_requests SET delivery_code='RFX-'||upper(substr(md5(random()::text||id::text||clock_timestamp()::text),1,8)) WHERE delivery_code IS NULL`);
 await pool.query('CREATE UNIQUE INDEX IF NOT EXISTS idx_delivery_requests_delivery_code ON delivery_requests(delivery_code)');await pool.query('ALTER TABLE delivery_requests ALTER COLUMN delivery_code SET NOT NULL');
 await pool.query(`CREATE TABLE IF NOT EXISTS rider_ratings(id SERIAL PRIMARY KEY,delivery_request_id INTEGER NOT NULL REFERENCES delivery_requests(id),rider_id INTEGER NOT NULL REFERENCES users(id),dispatcher_id INTEGER REFERENCES users(id),retailer_id INTEGER REFERENCES users(id),reviewer_role TEXT NOT NULL CHECK(reviewer_role IN ('dispatcher','retailer')),rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5),comment TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),CHECK((reviewer_role='dispatcher' AND dispatcher_id IS NOT NULL AND retailer_id IS NULL) OR (reviewer_role='retailer' AND retailer_id IS NOT NULL AND dispatcher_id IS NULL)))`);
 await pool.query('ALTER TABLE rider_ratings ALTER COLUMN dispatcher_id DROP NOT NULL');
 await pool.query('ALTER TABLE rider_ratings DROP CONSTRAINT IF EXISTS rider_ratings_delivery_request_id_key');
 await pool.query('ALTER TABLE rider_ratings ADD COLUMN IF NOT EXISTS retailer_id INTEGER REFERENCES users(id)');
 await pool.query('ALTER TABLE rider_ratings ADD COLUMN IF NOT EXISTS reviewer_role TEXT');
 await pool.query(`UPDATE rider_ratings SET reviewer_role=CASE WHEN retailer_id IS NOT NULL THEN 'retailer' ELSE 'dispatcher' END WHERE reviewer_role IS NULL`);
 await pool.query(`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='rider_ratings_reviewer_role_check') THEN ALTER TABLE rider_ratings ADD CONSTRAINT rider_ratings_reviewer_role_check CHECK (reviewer_role IN ('dispatcher','retailer')); END IF; END $$`);
 await pool.query('CREATE UNIQUE INDEX IF NOT EXISTS idx_rider_ratings_dispatcher_once ON rider_ratings(delivery_request_id,dispatcher_id) WHERE dispatcher_id IS NOT NULL');
 await pool.query('CREATE UNIQUE INDEX IF NOT EXISTS idx_rider_ratings_retailer_once ON rider_ratings(delivery_request_id,retailer_id) WHERE retailer_id IS NOT NULL');
 await pool.query('CREATE INDEX IF NOT EXISTS idx_rider_ratings_rider ON rider_ratings(rider_id,created_at DESC)');
 await pool.query(`CREATE TABLE IF NOT EXISTS delivery_request_state_cache(delivery_request_id INTEGER PRIMARY KEY REFERENCES delivery_requests(id) ON DELETE CASCADE,current_status delivery_status NOT NULL,status_updated_at TIMESTAMPTZ NOT NULL,rider_id INTEGER REFERENCES users(id))`);
 await pool.query(`CREATE OR REPLACE FUNCTION refresh_delivery_request_state_cache() RETURNS TRIGGER AS $$ DECLARE latest_rider INTEGER; BEGIN SELECT a.rider_id INTO latest_rider FROM assignments a WHERE a.delivery_request_id=NEW.delivery_request_id ORDER BY a.assigned_at DESC LIMIT 1; INSERT INTO delivery_request_state_cache(delivery_request_id,current_status,status_updated_at,rider_id) VALUES(NEW.delivery_request_id,NEW.status,NEW.created_at,latest_rider) ON CONFLICT(delivery_request_id) DO UPDATE SET current_status=EXCLUDED.current_status,status_updated_at=EXCLUDED.status_updated_at,rider_id=EXCLUDED.rider_id; RETURN NEW; END; $$ LANGUAGE plpgsql`);
 await pool.query(`CREATE OR REPLACE FUNCTION refresh_state_cache_rider() RETURNS TRIGGER AS $$ BEGIN UPDATE delivery_request_state_cache SET rider_id=NEW.rider_id WHERE delivery_request_id=NEW.delivery_request_id; RETURN NEW; END; $$ LANGUAGE plpgsql`);
 await pool.query('DROP TRIGGER IF EXISTS trg_status_event_state_cache ON status_events');await pool.query('DROP TRIGGER IF EXISTS trg_assignment_state_cache ON assignments');await pool.query('CREATE TRIGGER trg_status_event_state_cache AFTER INSERT ON status_events FOR EACH ROW EXECUTE FUNCTION refresh_delivery_request_state_cache()');await pool.query('CREATE TRIGGER trg_assignment_state_cache AFTER INSERT ON assignments FOR EACH ROW EXECUTE FUNCTION refresh_state_cache_rider()');
 await pool.query(`INSERT INTO delivery_request_state_cache(delivery_request_id,current_status,status_updated_at,rider_id) SELECT latest.delivery_request_id,latest.status,latest.created_at,a.rider_id FROM (SELECT DISTINCT ON(delivery_request_id) delivery_request_id,status,created_at FROM status_events ORDER BY delivery_request_id,created_at DESC) latest LEFT JOIN LATERAL(SELECT rider_id FROM assignments WHERE delivery_request_id=latest.delivery_request_id ORDER BY assigned_at DESC LIMIT 1)a ON true ON CONFLICT(delivery_request_id) DO UPDATE SET current_status=EXCLUDED.current_status,status_updated_at=EXCLUDED.status_updated_at,rider_id=EXCLUDED.rider_id`);
 await pool.query('DROP VIEW IF EXISTS delivery_request_state');await pool.query(`CREATE VIEW delivery_request_state AS SELECT dr.id,dr.retailer_id,dr.customer_name,dr.customer_phone,dr.address,dr.item_description,dr.delivery_code,dr.created_at,c.current_status,c.status_updated_at,c.rider_id FROM delivery_requests dr JOIN delivery_request_state_cache c ON c.delivery_request_id=dr.id`);
}
async function markStuckInTransit(){const client=await pool.connect();try{const {rows}=await client.query(`SELECT latest.delivery_request_id,latest.actor_id AS rider_id,dr.retailer_id FROM(SELECT DISTINCT ON(se.delivery_request_id) se.delivery_request_id,se.status,se.actor_id,se.created_at FROM status_events se ORDER BY se.delivery_request_id,se.created_at DESC)latest JOIN delivery_requests dr ON dr.id=latest.delivery_request_id WHERE latest.status='PICKED_UP' AND latest.created_at<=now()-($1*interval '1 hour')`,[limits.stuckInTransitHours]);for(const d of rows){const e=await client.query(`INSERT INTO status_events(delivery_request_id,status,actor_id,metadata) SELECT $1,'STUCK_IN_TRANSIT',$2,$3 WHERE NOT EXISTS(SELECT 1 FROM status_events WHERE delivery_request_id=$1 AND status='STUCK_IN_TRANSIT' AND created_at>now()-($4*interval '1 hour')) RETURNING *`,[d.delivery_request_id,d.rider_id,JSON.stringify({automatic:true,reason:`No delivery confirmation within ${limits.stuckInTransitHours} hours of pickup`,threshold_hours:limits.stuckInTransitHours}),limits.stuckInTransitHours+1]);if(e.rows.length)wsHub.broadcastStatusEvent(e.rows[0],{retailerId:d.retailer_id,riderId:d.rider_id});}}catch(err){console.error('[reflex] Stuck-in-transit monitor failed:',err);}finally{client.release();}}
if(require.main===module)initializeDatabase().then(ensureSchemaUpgrades).then(()=>server.listen(PORT,()=>{console.log(`Reflex backend listening on port ${PORT}`);markStuckInTransit();setInterval(markStuckInTransit,limits.stuckMonitorMinutes*60*1000);})).catch(async error=>{console.error('[reflex] Database initialization failed:',error);await pool.end();process.exit(1);});
module.exports={app,server};
