const express=require('express');const {pool}=require('../db');const {requireAuth,requireRole}=require('../auth');const {limits}=require('../config');
const router=express.Router();
router.post('/deliveries/:deliveryId',requireAuth,requireRole('dispatcher','retailer'),async(req,res)=>{const deliveryId=Number(req.params.deliveryId);const rating=Number(req.body.rating);const comment=typeof req.body.comment==='string'?req.body.comment.trim().slice(0,limits.commentMaxLength):null;if(!Number.isInteger(deliveryId)||deliveryId<1)return res.status(400).json({error:'Invalid delivery id'});if(!Number.isInteger(rating)||rating<1||rating>5)return res.status(400).json({error:'Rating must be a whole number from 1 to 5'});if(typeof req.body.comment==='string'&&req.body.comment.trim().length>limits.commentMaxLength)return res.status(400).json({error:`Comment must be ${limits.commentMaxLength} characters or fewer`});const client=await pool.connect();try{await client.query('BEGIN');const result=await client.query('SELECT s.current_status,s.rider_id,s.retailer_id FROM delivery_request_state s WHERE s.id=$1 FOR UPDATE',[deliveryId]);if(!result.rows.length){await client.query('ROLLBACK');return res.status(404).json({error:'Delivery not found'});}const delivery=result.rows[0];if(delivery.current_status!=='DELIVERED'){await client.query('ROLLBACK');return res.status(409).json({error:'A rider can only be rated after the delivery is DELIVERED'});}if(!delivery.rider_id){await client.query('ROLLBACK');return res.status(409).json({error:'Delivered delivery has no assigned rider'});}if(req.user.role==='retailer'&&Number(delivery.retailer_id)!==Number(req.user.id)){await client.query('ROLLBACK');return res.status(403).json({error:'Only the retailer who created this delivery can rate it'});}if(req.user.role==='dispatcher'){const assignment=await client.query('SELECT id FROM assignments WHERE delivery_request_id=$1 AND rider_id=$2 AND assigned_by=$3 ORDER BY assigned_at DESC LIMIT 1',[deliveryId,delivery.rider_id,req.user.id]);if(!assignment.rows.length){await client.query('ROLLBACK');return res.status(403).json({error:'Only the dispatcher who assigned this rider can rate the delivery'});}}const reviewerRole=req.user.role;const dispatcherId=reviewerRole==='dispatcher'?req.user.id:null;const retailerId=reviewerRole==='retailer'?req.user.id:null;const inserted=await client.query(`INSERT INTO rider_ratings(delivery_request_id,rider_id,dispatcher_id,retailer_id,reviewer_role,rating,comment) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT DO NOTHING RETURNING *`,[deliveryId,delivery.rider_id,dispatcherId,retailerId,reviewerRole,rating,comment]);if(!inserted.rows.length){await client.query('ROLLBACK');return res.status(409).json({error:`This delivered order has already been rated by this ${reviewerRole}`});}await client.query('COMMIT');res.status(201).json({rating:inserted.rows[0]});}catch(err){try{await client.query('ROLLBACK')}catch{}console.error(err);res.status(500).json({error:'Internal error'});}finally{client.release();}});
router.get('/rider/:riderId',requireAuth,async(req,res)=>{const riderId=Number(req.params.riderId);if(!Number.isInteger(riderId)||riderId<1)return res.status(400).json({error:'Invalid rider id'});if(!['rider','dispatcher','retailer'].includes(req.user.role)||(req.user.role==='rider'&&Number(req.user.id)!==riderId))return res.status(403).json({error:'You are not allowed to view this rider rating'});try{const {rows}=await pool.query(`SELECT rr.id,rr.delivery_request_id,rr.rating,rr.comment,rr.created_at,rr.reviewer_role,u.name AS reviewer_name FROM rider_ratings rr LEFT JOIN users u ON u.id=COALESCE(rr.dispatcher_id,rr.retailer_id) WHERE rr.rider_id=$1 ORDER BY rr.created_at DESC`,[riderId]);const avg=rows.length?Number((rows.reduce((sum,r)=>sum+Number(r.rating),0)/rows.length).toFixed(2)):null;
// Bug fix: this used to reference s.delivery_request_id, which doesn't
// exist on the delivery_request_state view (its column is just "id") —
// this threw a Postgres error on every call, and because this route had
// no try/catch, the unhandled rejection crashed the entire Node process,
// not just this one request. Fixed to reference a.delivery_request_id
// (the assignments row already carries it) and wrapped in try/catch so
// any future query error degrades to a 500 instead of taking the whole
// server down for every user.
const stats=await pool.query(`SELECT COUNT(DISTINCT a.delivery_request_id)::int AS deliveries_assigned,COUNT(DISTINCT CASE WHEN s.current_status='DELIVERED' THEN a.delivery_request_id END)::int AS deliveries_completed,COUNT(DISTINCT CASE WHEN s.current_status='FAILED' THEN a.delivery_request_id END)::int AS deliveries_failed FROM assignments a LEFT JOIN delivery_request_state s ON s.id=a.delivery_request_id WHERE a.rider_id=$1`,[riderId]);res.json({rider_id:riderId,average_rating:avg,rating_count:rows.length,deliveries_assigned:stats.rows[0].deliveries_assigned,deliveries_completed:stats.rows[0].deliveries_completed,deliveries_failed:stats.rows[0].deliveries_failed,ratings:rows});}catch(err){console.error(err);res.status(500).json({error:'Internal error'});}});
router.get('/riders',requireAuth,requireRole('dispatcher'),async(req,res)=>{const {rows}=await pool.query(`SELECT u.id,u.name,u.phone,ROUND(AVG(rr.rating)::numeric,2) AS average_rating,COUNT(rr.id)::int AS rating_count FROM users u LEFT JOIN rider_ratings rr ON rr.rider_id=u.id WHERE u.role='rider' GROUP BY u.id,u.name,u.phone ORDER BY u.name`);res.json({riders:rows.map(r=>({...r,average_rating:r.average_rating===null?null:Number(r.average_rating)}))});});module.exports=router;
